version: '2'

services:
  db:
    build: ./docker/db
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: karaokeAPI
      MYSQL_DATABASE: karaokeAPI
      MYSQL_USER: karaoke
      MYSQL_PASSWORD: karaokeAPI
    ports:
      - "3306:3306"  
    volumes: 
      - ./mysql/:/var/lib/mysql
  web:
    build: . 
    volumes:
      - .:/code/app
    ports: 
      - 80:80
    depends_on:
      - db   