version: '2'

services:
  db:
    build: ./docker/db
    restart: always
    command: --max_allowed_packet=32505856
    env_file: .env
    ports:
      - "3306:3306"  
    volumes: 
      - ./mysql/:/var/lib/mysql
      - ./test/:/test
  web:
    build: . 
    volumes:
      - .:/code/app
    ports: 
      - 80:80
    depends_on:
      - db   
  dropbox:
    image: skidvis/mysql-backup-dropbox
    restart: always
    env_file: .env